
# default_yaml: ../finetune_3B.yaml
default_yaml: /workspace/jaeyoung/dcase2024_retrieval/ONE-PEACE/one_peace/run_scripts/finetune_3B.yaml

task:
  _name: audio_text_retrieval
  # data: /workspace/jaeyoung/data/WavText5K/processed_wavtext5k.csv
  data: /workspace/jaeyoung/data/clotho_dataset/merged_clotho_development.csv
  valid_data: /workspace/jaeyoung/data/clotho_dataset/merged_clotho_validation.csv
  # selected_cols: file_name,caption_1,caption_2,caption_3,caption_4,caption_5,keywords,sound_id
  selected_cols: file_name,caption_1,sound_id
  # selected_cols: title,description,fname,tags
  valid_file: /workspace/jaeyoung/data/clotho_dataset/merged_clotho_validation.csv

  max_duration: 20
  head_type: al

criterion:
  _name: audio_text_retrieval_criterion
  label_smoothing: 0.0

optimization:
  max_epoch: 10
  lr: [1.5e-4]
  update_freq: [1]
  skip_remainder_batch: false

dataset:
  batch_size: 8
  ensure_equal_batch: true

common:
  layer_decay: 0.95
  # tensorboard_logdir: /workspace/jaeyoung/checkpoints/tensorboard/onepeace_finetuned_jy

checkpoint:
  best_checkpoint_metric: txt_r1
  save_dir: /workspace/jaeyoung/checkpoints/onepeace_finetuned_jy

model:
  _name: one_peace_retrieval
  copy_rel_pos_table: true
  encoder:
    drop_path_rate: 0.9